### ISSUE TITLE
Expand client meta information

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Client.Web#364]
## Description

As a developer I want to be able to get detailed meta information on the client 

## Acceptance criteria

- [x] Create file that is created as part of image build
- [x] Additional meta information:  image build date
- [x] Additional data displayed in console panel
